version = 0.1

[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "ec2-images-analysis"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
profile = "AWSAdministratorAccess-354458181052"
s3_bucket = "your-s3-bucket-name"
s3_prefix = "ec2-images-analysis"
confirm_changeset = true
image_repositories = []
